workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app
        script: |
          xcodebuild build -workspace ios/Runner.xcworkspace -scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
