workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Instalar dependencias
        script: |
          cd ios
          pod repo update
          pod install --verbose
      - name: Compilar con Xcode
        script: |
          xcodebuild clean build -workspace ios/Runner.xcworkspace -scheme Runner CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - build/ios/ipa/*.ipa
